[package]
name = "mongobar"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
mongodb = "3.0.0"
anyhow = "1.0.86"
serde_json = "1.0.115"
serde = { version = "1.0.197", features = ["derive"] }
bson = "2.11.0"
chrono = { version = "0.4.38", features = ["serde"] }
