name: SyncToGitee
on:
  - push
  - pull_request
jobs:
  sync:
    name: sync
    runs-on: ubuntu-latest
    steps:
      - name: sync to gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/Lydanne
          dst: gitee/WumaCoder
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "mongobar"
